Name : Meharsh Chandure <br>
Roll No : A-36

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
print("--- Intermediate Pandas Exercise ---")
print("Complete each task by writing the requested Pandas code.")
print("------------------------------------")

# Task 1: Basic Pandas Functions and Converting Arrays to DataFrames
print("\n--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---")
# 1.1 Create a Pandas Series named 's1_1' from a list of numbers [10, 20, 30, 40, 50].
# 1.2 Create a 3x4 NumPy array named 'np_array1_2' with random integers between 1 and 100.
# 1.3 Convert 'np_array1_2' into a Pandas DataFrame named 'df1_3' with columns 'A', 'B', 'C', 'D'.

# Your code for Task 1 here:
s1_1 = pd.Series([10, 20, 30, 40, 50])
np_array1_2 = np.random.randint(1, 101, size=(3, 4))
df1_3 = pd.DataFrame(np_array1_2, columns=['A', 'B', 'C', 'D'])

print("s1_1:")
print(s1_1)
print("\nnp_array1_2:")
print(np_array1_2)
print("\ndf1_3:")
print(df1_3)

--- Intermediate Pandas Exercise ---
Complete each task by writing the requested Pandas code.
------------------------------------

--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---
s1_1:
0    10
1    20
2    30
3    40
4    50
dtype: int64

np_array1_2:
[[78 40 43 74]
 [57 40 56 11]
 [19 45 51 44]]

df1_3:
    A   B   C   D
0  78  40  43  74
1  57  40  56  11
2  19  45  51  44


In [ ]:
# Task 2: Synthetic Data Generation for Practice
print("\n--- Task 2: Synthetic Data Generation for Practice ---")
# Create a DataFrame named 'df_sales' with 100 rows and the following columns:
# - 'Date': A range of dates from '2023-01-01' to '2023-04-09' (inclusive).
# - 'Region': Randomly chosen from ['East', 'West', 'North', 'South'].
# - 'Product': Randomly chosen from ['Laptop', 'Mouse', 'Keyboard', 'Monitor'].
# - 'Sales': Random integers between 100 and 1000.
# - 'Quantity': Random integers between 1 and 10.
# - Introduce 5 random NaN values in the 'Sales' column and 3 random NaN values in the 'Quantity' column.

# Your code for Task 2 here:
dates = pd.date_range(start='2023-01-01', periods=100)
np.random.seed(42)
regions = np.random.choice(['East', 'West', 'North', 'South'], size=100)
products = np.random.choice(['Laptop', 'Mouse', 'Keyboard', 'Monitor'], size=100)
sales = np.random.randint(100, 1001, size=100)
quantity = np.random.randint(1, 11, size=100)
df_sales = pd.DataFrame({
    'Date': dates,
    'Region': regions,
    'Product': products,
    'Sales': sales,
    'Quantity': quantity
})
nan_sales_indices = np.random.choice(df_sales.index, size=5, replace=False)
df_sales.loc[nan_sales_indices, 'Sales'] = np.nan

nan_quantity_indices = np.random.choice(df_sales.index.difference(nan_sales_indices), size=3, replace=False)
df_sales.loc[nan_quantity_indices, 'Quantity'] = np.nan
print(df_sales.head())


--- Task 2: Synthetic Data Generation for Practice ---
        Date Region   Product  Sales  Quantity
0 2023-01-01  North  Keyboard  674.0       7.0
1 2023-01-02  South     Mouse  963.0       4.0
2 2023-01-03   East     Mouse    NaN       7.0
3 2023-01-04  North   Monitor  340.0       8.0
4 2023-01-05  North     Mouse  663.0       1.0


In [ ]:
# Task 3: Indexing and Slicing in DataFrames
print("\n--- Task 3: Indexing and Slicing in DataFrames ---")
# Use 'df_sales' from Task 2.
# 3.1 Select only the 'Region' and 'Sales' columns. Store it in 'df3_1'.
# 3.2 Select rows where 'Product' is 'Laptop'. Store it in 'df3_2'.
# 3.3 Select rows where 'Region' is 'East' AND 'Sales' are greater than 500. Store it in 'df3_3'.
# 3.4 Select the 'Sales' value for the first entry where 'Product' is 'Monitor' (use .loc and .iloc). Store it in 'val3_4'.

df3_1 = df_sales[['Region', 'Sales']]
df3_2 = df_sales[df_sales['Product'] == 'Laptop']
df3_3 = df_sales[(df_sales['Region'] == 'East') & (df_sales['Sales'] > 500)]
val3_4 = df_sales.loc[df_sales['Product'] == 'Monitor', 'Sales'].iloc[0]

print("df3_1:")
print(df3_1)
print("\ndf3_2:")
print(df3_2)
print("\ndf3_3:")
print(df3_3)


--- Task 3: Indexing and Slicing in DataFrames ---
df3_1:
   Region  Sales
0   North  674.0
1   South  963.0
2    East    NaN
3   North  340.0
4   North  663.0
..    ...    ...
95   West  152.0
96   West  783.0
97  South  829.0
98   West  771.0
99   East  809.0

[100 rows x 2 columns]

df3_2:
         Date Region Product  Sales  Quantity
16 2023-01-17  South  Laptop  624.0       4.0
19 2023-01-20  North  Laptop  798.0      10.0
21 2023-01-22   East  Laptop  185.0       3.0
24 2023-01-25  South  Laptop  781.0       4.0
27 2023-01-28   West  Laptop  745.0       8.0
31 2023-02-01   East  Laptop  655.0       1.0
32 2023-02-02  South  Laptop  439.0       9.0
33 2023-02-03   West  Laptop  897.0       9.0
35 2023-02-05   East  Laptop  739.0       7.0
36 2023-02-06  South  Laptop  605.0      10.0
37 2023-02-07   East  Laptop  447.0       3.0
39 2023-02-09  North  Laptop  330.0      10.0
41 2023-02-11  North  Laptop  324.0       4.0
48 2023-02-18   West  Laptop  358.0       9.0
52 2023-02-22  

In [ ]:
# Task 4: Data Cleaning (Handling Missing Values)
print("\n--- Task 4: Data Cleaning (Handling Missing Values) ---")
# Use 'df_sales' from Task 2 (which should have NaNs).
# 4.1 Check how many missing values are in each column. Store the result in 'missing_counts4_1'.
# 4.2 Fill missing 'Sales' values with the mean of the 'Sales' column. Store the modified DataFrame in 'df4_2_filled'.
# 4.3 Drop rows that have any missing values in 'df_sales'. Store the result in 'df4_3_dropped'.

missing_counts4_1 = df_sales.isna().sum()
print("\n4.1 Missing values in each column:\n", missing_counts4_1)

sales_mean = df_sales['Sales'].mean()
df4_2_filled = df_sales.copy()
df4_2_filled['Sales'] = df4_2_filled['Sales'].fillna(sales_mean)
print("\n4.2 Filled missing 'Sales' with mean:", sales_mean)

df4_3_dropped = df_sales.dropna()
print("\n4.3 After dropping rows with any missing values, shape:", df4_3_dropped.shape)


--- Task 4: Data Cleaning (Handling Missing Values) ---

4.1 Missing values in each column:
 Date        0
Region      0
Product     0
Sales       5
Quantity    3
dtype: int64

4.2 Filled missing 'Sales' with mean: 590.1473684210526

4.3 After dropping rows with any missing values, shape: (92, 5)


In [ ]:
# Task 5: Data Manipulation (Columns, Sorting, Grouping)
print("\n--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---")
# Use 'df_sales' (the original one with NaNs)
# 5.1 Create a new column 'Total_Revenue' which is 'Sales' * 'Quantity'.
#     (Be mindful of NaNs, the result should also be NaN where either Sales or Quantity is NaN).
# 5.2 Sort 'df_sales' by 'Date' in ascending order, then by 'Sales' in descending order. Store it in 'df5_2_sorted'.
# 5.3 Group 'df_sales' by 'Region' and calculate the sum of 'Sales' and 'Quantity' for each region.
#     Store the result in 'df5_3_grouped_region'.
# 5.4 Group 'df_sales' by 'Product' and find the average 'Sales' for each product.
#     Store the result in 'df5_4_grouped_product'.

df_sales['Total_Revenue'] = df_sales['Sales'] * df_sales['Quantity']
df5_2_sorted = df_sales.sort_values(by=['Date', 'Sales'], ascending=[True, False])
df5_3_grouped_region = df_sales.groupby('Region')[['Sales', 'Quantity']].sum()
df5_4_grouped_product = df_sales.groupby('Product')['Sales'].mean()

print("\n5.1 New column 'Total_Revenue':")
print(df_sales[['Sales', 'Quantity', 'Total_Revenue']])
print("\n5.2 Sorted DataFrame 'df5_2_sorted':")
print(df5_2_sorted)
print("\n5.3 Grouped DataFrame 'df5_3_grouped_region':")
print(df5_3_grouped_region)
print("\n5.4 Grouped DataFrame 'df5_4_grouped_product':")
print(df5_4_grouped_product)


--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---

5.1 New column 'Total_Revenue':
    Sales  Quantity  Total_Revenue
0   674.0       7.0         4718.0
1   963.0       4.0         3852.0
2     NaN       7.0            NaN
3   340.0       8.0         2720.0
4   663.0       1.0          663.0
..    ...       ...            ...
95  152.0       6.0          912.0
96  783.0       8.0         6264.0
97  829.0       2.0         1658.0
98  771.0       5.0         3855.0
99  809.0       1.0          809.0

[100 rows x 3 columns]

5.2 Sorted DataFrame 'df5_2_sorted':
         Date Region   Product  Sales  Quantity  Total_Revenue
0  2023-01-01  North  Keyboard  674.0       7.0         4718.0
1  2023-01-02  South     Mouse  963.0       4.0         3852.0
2  2023-01-03   East     Mouse    NaN       7.0            NaN
3  2023-01-04  North   Monitor  340.0       8.0         2720.0
4  2023-01-05  North     Mouse  663.0       1.0          663.0
..        ...    ...       ...    ...      